using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MonResto.Data.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Migration logic would be generated by EF Core tools.
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Reverse changes.
        }
    }
}
